# Use the python language default and install R as we need.  The travis version
# of R was too difficult to update with everything we need compared to just
# installing it in the python container.
language: python

python:
  - "2.7"
  - "3.5"

cache:
  packages: true
  pip: true
  directories:
    - $HOME/.cache
    - $HOME/build/osumo/osumo/_build/store
    - $HOME/build/osumo/osumo/_build/data
    - $HOME/build/env/conda2
    - $HOME/build/env/conda3
sudo: false

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]] ; then PY=2 ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]] ; then PY=3 ; fi
  - CONDA_DIR="$HOME/build/env/conda${PY}"
  - wget -O conda.bash "https://repo.continuum.io/miniconda/Miniconda${PY}-latest-Linux-x86_64.sh"
  - bash conda.bash -b -f -p "$CONDA_DIR"
  - export PATH="$CONDA_DIR/bin:$PATH"
  - conda env update -f environment.yml
  - source activate testing
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install v6
  - nvm use v6
  - npm config set python `which python`
  - npm install -g npm

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]] ; then PY=2 ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]] ; then PY=3 ; fi
  - CONDA_DIR="$HOME/build/env/conda${PY}"
  - export PATH="$CONDA_DIR/bin:$PATH"
  - source activate testing
  - pip install -r requirements.txt
  - npm install

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]] ; then PY=2 ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]] ; then PY=3 ; fi
  - CONDA_DIR="$HOME/build/env/conda${PY}"
  - export PATH="$CONDA_DIR/bin:$PATH"
  - source activate testing
  - npm run lint

