# Use the python language default and install R as we need.  The travis version
# of R was too difficult to update with everything we need compared to just
# installing it in the python container.
language: python
cache:
  packages: true
  pip: true
  directories:
    - $HOME/.cache
    - $HOME/build/osumo/osumo/_build/store
    - $HOME/build/osumo/osumo/_build/data
sudo: false

before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install v6
  - nvm use v6
  - npm config set python `which python`
  - npm install -g npm

script:
  - npm install
  - npm run lint

