# Use the R language default, as travis always has Python
language: python
cache:
  packages: true
  pip: true
  directories:
    - $HOME/.cache
    - $HOME/build/osumo/osumo/_build/data/plugins/osumo
sudo: false

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # I doubt all of these are necessary, but I'm having trouble getting the
      # latest version of node, which is necessary for the webpack stuff
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - zip
      - libgtk2.0-0
      - python-dev
      - gsl-dev
      - r-base-dev

before_install:
  - main_path=$PWD
  - build_path=$main_path/build
  - mkdir -p $build_path
  
  - R_LIBS=$HOME/.cache/R
  - R_LIBS_USER=$R_LIBS
  - mkdir -p $R_LIBS || true

  - pip install -U pip virtualenv
  - mkdir -p $main_path/env
  - virtualenv $main_path/env
  - source $main_path/env/bin/activate
  - pip install --upgrade pip

  # Use Node 5.10
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install 5.10
  - nvm use 5.10
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - cd $main_path

  - girder_path=$HOME/girder
  - rm -fr $girder_path
  - git clone https://github.com/girder/girder.git $girder_path && git -C $girder_path checkout a381b5822b1fb063e3d8877fc1a6ff629e52eebf
  - ln -sf $main_path $girder_path/plugins/
  - ls -l $girder_path/plugins

  - CACHE=$HOME/.cache CMAKE_VERSION=3.1.0 CMAKE_SHORT_VERSION=3.1 source $girder_path/scripts/install_cmake.sh
  - cmake --version

  - girder_worker_path=$HOME/girder_worker
  - git clone https://github.com/girder/girder_worker.git $girder_worker_path && git -C $girder_worker_path checkout 4429c6e98b2b11d47edb43390571551ab2d36749
  - cp $main_path/testing/travis/girder_worker.local.cfg $girder_worker_path/girder_worker/worker.local.cfg
  - pip install -U -r $girder_worker_path/requirements.txt -r $girder_worker_path/girder_worker/plugins/girder_io/requirements.txt -r $girder_worker_path/girder_worker/plugins/r/requirements.txt

  - export MONGO_VERSION=3.2.6
  - export PY_COVG="ON"
  - CACHE=$HOME/.cache source $girder_path/scripts/install_mongo.sh
  - mkdir /tmp/db
  - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
  - mongod --version

  - mkdir -p $HOME/.cache/node_modules || true
  - ln -sf $HOME/.cache/node_modules .
  - npm install -g npm
  - npm prune
  - npm install -g npm
  - npm --version

  - ln -s $main_path $girder_path/plugins/osumo

install:
  - cd $girder_path
  - pip install -U -r requirements.txt -r requirements-dev.txt
  # - pip install --no-cache-dir -e .
  - npm install
  - R -e "install.packages(c('cccd', 'cluster', 'igraph', 'jsonlite', 'pheatmap', 'survival'), repos='http://cran.rstudio.com')"

script:
  - cd $girder_worker_path
  - python -m girder_worker >/tmp/worker.out 2>&1 &  # #DWM::
  - cd $main_path
  - mkdir -p _build
  - cd _build
  # Our coverage numbers are small, because we aren't testing all of girder
  - cmake -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} -DPYTHON_COVERAGE:BOOL=YES -DCOVERAGE_MINIMUM_PASS=40 -DJS_COVERAGE_MINIMUM_PASS=9 $girder_path
  - make
  - cat /tmp/worker.out  # ##DWM::
  - JASMINE_TIMEOUT=15000 ctest -VV -R '(py_coverage_reset|py_coverage_combine|py_coverage$|coverage_xml|osumo)'
