
name: OSUMO
version: 0.0.1
description: "Multi-Omics Data Analytics @ OSU"
grunt:
    autobuild: false
    dependencies:
        "webpack": 2.1.0-beta.4
    file: Gruntfile.js
dependencies:
    - worker
    - jobs

