
name: OSUMO
version: 0.0.1
description: "**M**ulti-**O**mics Data Analytics @ **OSU**"
grunt:
    autobuild: false
    dependencies:
        "webpack": 2.0.6-beta
    file: Gruntfile.js
dependencies:
    - worker
    - jobs

