
name: OSUMO
version: 0.0.1
description: "Multi-Omics Data Analytics @ OSU"
npm:
  file: package.json
  fields:
    - dependencies
    - devDependencies
webpack:
  configHelper: webpack.helper.js
  main: web_client/main.jsx
  output: index
dependencies:
  - worker
  - jobs

